version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: web.docker
        # volumes:
        #     - ./:/var/www
        ports:
            - "80:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: app.docker
        ports:
            - "9000:9000"
        # volumes:
        #     - ./:/var/www