version: '2'
services:
    app:
        build:
            context: ./
            dockerfile: app.docker
        #volumes:
        #    - ./:/var/www
        ports:
            - "80:80"
            - "2222:22"            
